rename DGC to DCC
ehn-dcc-development/hcert-spec pull request #83
Opened 2021-05-26 11:53 UTC by jschlyter

2021-05-26 11:55 UTC, gabywh requested changes
1 typo, then it's good

2021-05-26 11:55 UTC, gabywh commented on hcert_spec.md
> +### 3.1 The European Digital Covide Certificate (DCC)
Covid not Covide

2021-06-10 11:20 UTC, martin-lindstrom commented
OK. Fine.

But before the next release we must also change the ISO 3166-1 alpha-2 requirement of the `iss`. The schema now supports organizations (such as UNHCR) instead of country codes.

2021-06-10 11:21 UTC, martin-lindstrom approved these changes

2021-06-10 11:24 UTC, merged